import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,createReadStream} from 'node:fs';
import {createHash} from 'node:crypto';
import {Renderer,sceneLayerAnimationFrame,npcTalkPlaybackFrame} from '../src/engine/Renderer.js';
import {chapter1} from '../src/content/chapter1/index.js';
import {assetManifest} from '../src/content/art/assetManifest.js';
import {imageAssetPaths} from '../src/engine/AssetLoader.js';
const mehana=chapter1.scenes.find(s=>s.id==='scene.chapter1.mehana');
const layer=mehana.foregroundLayers.find(l=>l.id==='layer.mehana.tony_fridge_seated');
const a=layer.talkAnimation;
test('Tony turns once and sustains only left-facing speaking frames over long lines',()=>{
 assert.deepEqual(Array.from({length:22},(_,i)=>sceneLayerAnimationFrame(a,i*187)),Array.from({length:22},(_,i)=>i));
 for(let i=22;i<500;i++)assert.ok(sceneLayerAnimationFrame(a,i*187)>=4&&sceneLayerAnimationFrame(a,i*187)<=21);
 assert.equal(sceneLayerAnimationFrame(a,22*187),4);
 assert.equal(sceneLayerAnimationFrame(a,40*187),4);
 const plain={frameCount:25,frameDurationMs:190,loop:true};
 assert.equal(sceneLayerAnimationFrame(plain,25*190),0);
 assert.equal(sceneLayerAnimationFrame({...plain,loop:false},50*190),24);
});
test('Tony return starts only after speech, freezes in menus, and restarts on another line',()=>{
 let result=npcTalkPlaybackFrame(a,5000,5000);
 assert.ok(result.frameIndex>=4&&result.frameIndex<=21);
 result=npcTalkPlaybackFrame(a,null,5016,result.state);assert.equal(result.frameIndex,22);
 result=npcTalkPlaybackFrame(a,null,5203,result.state);assert.equal(result.frameIndex,23);
 result=npcTalkPlaybackFrame(a,null,6203,result.state,true);assert.equal(result.frameIndex,23);
 result=npcTalkPlaybackFrame(a,null,6390,result.state);assert.equal(result.frameIndex,24);
 result=npcTalkPlaybackFrame(a,null,6577,result.state);assert.equal(result.frameIndex,null);
 result=npcTalkPlaybackFrame(a,0,6600,result.state);assert.equal(result.frameIndex,0);
 result=npcTalkPlaybackFrame(a,null,6616,result.state);assert.equal(result.frameIndex,22);
 result=npcTalkPlaybackFrame(a,0,6632,result.state);assert.equal(result.frameIndex,0);
 assert.equal(npcTalkPlaybackFrame(a,null,0).frameIndex,null);
});
test('Tony talk and return preserve idle scale and anchor with missing-asset fallback',()=>{
 const talk={id:'talk'},idle={id:'idle'},fallback={id:'static',naturalWidth:914,naturalHeight:1166};
 const loaded=new Set([talk,idle,fallback]),calls=[];
 let speechTime=0;
 const game={lastTime:0,npcSpeechAnimationTime:()=>speechTime,assets:{getSceneImage:(_id,alias)=>alias===a.asset?talk:alias===layer.animation.asset?idle:fallback,isLoaded:img=>loaded.has(img)}};
 const renderer=Object.assign(Object.create(Renderer.prototype),{ctx:{drawImage:(...args)=>calls.push(args)},game});
 renderer.drawSceneRasterLayer(mehana,layer);
 const scale=320 / 198,rect=[877-2*scale,296+2*scale,156*scale,198*scale];
 assert.deepEqual(calls.at(-1).slice(5),rect);
 speechTime=8000;game.lastTime=8000;renderer.drawSceneRasterLayer(mehana,layer);assert.deepEqual(calls.at(-1).slice(5),rect);
 speechTime=null;game.lastTime=8016;renderer.drawSceneRasterLayer(mehana,layer);assert.equal(calls.at(-1)[0],talk);assert.equal(Math.floor(calls.at(-1)[2]/384)*5+Math.floor(calls.at(-1)[1]/384),22);
 loaded.delete(talk);renderer.drawSceneRasterLayer(mehana,layer);assert.equal(calls.at(-1)[0],idle);
 loaded.delete(idle);renderer.drawSceneRasterLayer(mehana,layer);assert.equal(calls.at(-1)[0],fallback);
 loaded.add(talk);loaded.add(idle);
 renderer.drawSceneRasterLayer({id:'different'}, {...layer,talkAnimation:undefined});
 renderer.drawSceneRasterLayer(mehana,layer);assert.equal(calls.at(-1)[0],idle);
});
test('Tony is preloaded only in Mehana; approved reference, idle and election remain stable',()=>{
 assert.deepEqual([layer.left,layer.top,layer.height,layer.zIndex],[877,296,320,35]);
 assert.deepEqual(layer.animation.contentBounds,{x:116,y:91,w:152,h:198});
 assert.deepEqual(a.registrationBounds,layer.animation.contentBounds);
 assert.equal(a.npcId,'npc.tony_fridge');assert.equal(a.frameDurationMs,187);
 assert.ok(imageAssetPaths(assetManifest.scenes[mehana.id]).includes(assetManifest.scenes[mehana.id].tonyFridgeTalkSeated));
 const election=chapter1.scenes.find(s=>s.id==='scene.chapter1.election_booth');
 assert.ok(election.foregroundLayers.every(l=>!l.talkAnimation));
 assert.equal(assetManifest.scenes[election.id].tonyFridgeTalkSeated,undefined);
 const sha=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
 assert.equal(sha('assets/chapter1/characters/tony_fridge/idle-seated-v1.webp'),'1cca1e9231c9401f01625f16913e124c0ac3728c2d10f05b862e2836f6e2fd7e');
 const pilot=JSON.parse(readFileSync('assets_src/characters/tony_fridge/external_animation_v1/animation-pilot.json'));
 assert.equal(pilot.animations.tony_idle_seated_1.status,'runtime_approved');
 assert.equal(pilot.animations.tony_talk_seated_1.source.sourceZipSha256,'51469c2e21de203e2aac6be1658ac78e1838dba898d58a9824feaf6761a9dc56');
});

test('Tony faces left through reply choices and later lines, returning only when the conversation closes',()=>{
 const session={id:'tony'},nextSession={id:'tony'};
 let r=npcTalkPlaybackFrame(a,0,0,{},false,session);
 assert.equal(r.frameIndex,0);
 r=npcTalkPlaybackFrame(a,null,1000,r.state,false,session);
 assert.equal(r.frameIndex,4);
 r=npcTalkPlaybackFrame(a,null,10000,r.state,false,session);
 assert.equal(r.frameIndex,4);assert.equal(r.state.phase,'conversation');
 r=npcTalkPlaybackFrame(a,0,10016,r.state,false,session);
 assert.ok(r.frameIndex>=4&&r.frameIndex<=21);
 const elapsed=r.state.elapsed;
 r=npcTalkPlaybackFrame(a,0,12016,r.state,true,session);
 assert.equal(r.state.elapsed,elapsed);
 r=npcTalkPlaybackFrame(a,null,12032,r.state,false,session);
 assert.equal(r.frameIndex,4);
 r=npcTalkPlaybackFrame(a,null,12048,r.state);
 assert.equal(r.frameIndex,22);
 r=npcTalkPlaybackFrame(a,null,12609,r.state);
 assert.equal(r.frameIndex,null);
 r=npcTalkPlaybackFrame(a,0,13000,r.state,false,nextSession);
 assert.equal(r.frameIndex,0);
});
