export const bg = {
  "game.title": "Другарят Кандидат",
  "chapter1.title": "Изборен ден на село",
  "scene.chapter1.apartment.title": "Апартаментът на Бай Митко",
  "scene.chapter1.village_square.title": "Селският площад",
  "scene.chapter1.mehana.title": "Механа \"Двете кози\"",

  "ui.new_game": "Нова игра",
  "ui.continue": "Продължи",
  "ui.language": "Език",
  "ui.pause": "Пауза",
  "ui.resume": "Назад",
  "ui.save": "Запази",
  "ui.menu": "Меню",
  "ui.restart": "Започни отначало",
  "ui.main_menu": "Главно меню",
  "ui.restart_confirm": "Да започна ли Глава 1 отначало и да изтрия текущия запис?",
  "ui.reset": "Изтрий",
  "ui.reset_confirm": "Да изтрия ли текущата игра, джобовете и всички записани предмети?",
  "ui.quests": "Задачи",
  "ui.quests.outstanding": "Незавършени: {count}",
  "ui.quests.none": "Няма незавършени задачи.",
  "ui.quests.tab.outstanding": "Незавършени",
  "ui.quests.tab.completed": "Завършени",
  "ui.quests.tab_with_count": "{tab}: {count}",
  "ui.quests.outstanding.none": "Няма незавършени задачи.",
  "ui.quests.completed.none": "Все още няма завършени задачи.",
  "ui.hud": "Състояние на играта",
  "ui.inventory": "Инвентар",
  "ui.inventory.use": "Използвай",
  "ui.inventory.use_on_self": "Използвай върху Бай Митко",
  "ui.inventory.inspect": "Разгледай",
  "ui.inventory.drop": "Изхвърли",
  "ui.inventory.close": "Затвори",
  "ui.inventory.cancel": "Откажи",
  "ui.inventory.use_prompt": "Използвай {item} върху...",
  "ui.inventory.use_with_target": "Използвай {item} върху {target}",
  "ui.dropped_items.title": "Оставени наблизо",
  "ui.dropped_items.pick_up": "Прибери",
  "ui.dropped_items.close": "Затвори",
  "ui.verb": "Действие",
  "ui.meter.influence": "Влияние",
  "ui.meter.rakia": "Изпити ракии",
  "ui.intoxication.daisy": "Минзухар",
  "ui.intoxication.merry": "Почерпен",
  "ui.intoxication.tipsy": "Подпийнал",
  "ui.intoxication.plastered": "Мотика",
  "ui.meter.suspicion": "Подозрение",
  "ui.meter.public_mood": "Народно настроение",
  "ui.hint": "Ляв бутон: действие. Десен бутон: сменя действие. Esc: пауза.",
  "npc.bai_mitko.name": "Бай Митко",

  "verb.look": "Виж",
  "verb.talk": "Говори",
  "verb.use": "Използвай",
  "verb.take": "Вземи",

  "exit.to_village_square": "Към площада",
  "exit.to_apartment": "Към апартамента",
  "exit.to_mehana": "Към механата",
  "exit.to_municipality": "Към общината",

  "item.accordion.name": "Акордеон",
  "item.accordion.desc": "Единственото нещо, което Бай Митко някога е свирил честно.",
  "item.unpaid_bills.name": "Неплатени сметки",
  "item.unpaid_bills.desc": "Финансова автобиография с печален край.",
  "msg.apartment.unpaid_bills_taken": "Сметките са прибрани. Доказателства не се оставят на масата, освен ако не са за гости.",
  "item.empty_envelope.name": "Празен плик",
  "item.empty_envelope.desc": "Празен, но с административен потенциал.",
  "item.fake_diploma.name": "Фалшива диплома",
  "item.fake_diploma.desc": "Изглежда достатъчно официално за хора, които не гледат внимателно.",
  "item.rakia.name": "Бутилка ракия",
  "item.rakia.desc": "Течна демокрация с висок градус.",
  "item.shopska_salad.name": "Шопска салата",
  "item.shopska_salad.desc": "Домати, краставици и достатъчно сирене, за да не се вижда фискалната политика.",
  "item.tripe_soup.name": "Шкембе за вкъщи",
  "item.tripe_soup.desc": "Шкембе в буркан. Аварийна стабилизация с винтова капачка.",
  "item.village_wine.name": "Бутилка селско вино",
  "item.village_wine.desc": "Домашно вино с достатъчно характер, за да мине за официален посредник.",
  "item.sunflower_oil.name": "Олио",
  "item.sunflower_oil.desc": "Народна медицина срещу тежки политически решения.",
  "item.glass_of_water.name": "Чаша вода",
  "item.glass_of_water.desc": "Безцветна, безпартийна и подозрително трезва.",
  "item.campaign_pamphlets.name": "Предизборни листовки",
  "item.campaign_pamphlets.desc": "Обещания на тънка хартия.",
  "item.suspicious_receipt.name": "Подозрителна касова бележка",
  "item.suspicious_receipt.desc": "Пише касова, звучи съдебна.",
  "item.pickle_jar.name": "Буркан с кисели краставички",
  "item.pickle_jar.desc": "Консерва с по-добра програма от повечето кандидати.",
  "item.ballot_box.name": "Избирателна урна",
  "item.ballot_box.desc": "Прозрачна по закон, мътна по традиция.",
  "item.municipality_stamp.name": "Общински печат",
  "item.municipality_stamp.desc": "Един малък печат отваря голяма врата.",

  "hotspot.wallpaper.name": "Лющен тапет",
  "hotspot.window.name": "Прозорец",
  "hotspot.campaign_poster.name": "Проектоплакат",
  "hotspot.mirror.name": "Напукано огледало",
  "hotspot.tv.name": "Стар телевизор",
  "hotspot.wardrobe.name": "Гардероб",
  "hotspot.table.name": "Евтина маса",
  "hotspot.poster_board.name": "Агитационно табло",
  "hotspot.fountain.name": "Фонтан",
  "hotspot.kiosk.name": "Вестникарска будка",
  "hotspot.statue.name": "Паметник",
  "hotspot.old_men_bench.name": "Пейка на старците",
  "hotspot.election_notice.name": "Изборно съобщение",
  "hotspot.square.mehana_menu.name": "Менюто на механата",
  "hotspot.dropped_items.name": "Оставени вещи",
  "hotspot.water_jug.name": "Кана с вода",
  "hotspot.mehana_table.name": "Маса в механата",
  "hotspot.mehana.bai_mitko_rakia_glass.name": "Чашата на Бай Митко",
  "hotspot.mehana.tony_rakia_glass.name": "Чашата на Тони",
  "hotspot.apartment.rakia_bottle.name": "Шише с ракия",
  "hotspot.apartment.bed.name": "Разтегателен диван",

  "npc.baba_stoyanka.name": "Баба Стоянка",
  "npc.tony_fridge.name": "Тони Хладилника",
  "npc.mehana_waiter.name": "Сервитьорът Киро",

  "look.apartment.wallpaper": "Тапетът се лющи с тихото достойнство на пенсиониран министър.",
  "look.apartment.window": "Прозорец към чист въздух, доколкото районът позволява.",
  "look.apartment.accordion": "Моят акордеон. Единственото нещо, което някога съм свирил честно.",
  "look.apartment.mirror": "Огледалото го показва на три части. Коалиционно излъчване.",
  "look.apartment.tv": "Телевизорът пак обяснява, че ситуацията е стабилна, но с извънреден характер.",
  "look.apartment.wardrobe": "Гардеробът пази дрехи от времена, когато Бай Митко още имаше план Б.",
  "look.apartment.table": "Маса за сметки, обещания и други хартиени трагедии.",
  "look.apartment.rakia_bottle": "Домашна ракия. Етикет няма, защото истината не се нуждае от документация.",
  "look.apartment.bed": "Разтегателен диван. Денем коалиция, нощем мнозинство.",
  "msg.apartment.nap": "Бай Митко дремна служебно. Светът пак има един хоризонт.",
  "msg.apartment.window_opened": [
    "Мммм. Мирише ми на избори.",
    "Май някой пак е проветрил коалицията."
  ],
  "look.apartment.poster": "ГЛАСУВАЙ ЗА МИТКО: ПОНЕ ГО ПОЗНАВАШ. Силна програма, ако населението няма избор.",
  "look.square.poster_board": "Плакат върху плакат върху обещание. Археология на надеждата.",
  "look.square.fountain": "Фонтанът не работи, но поне не краде ток.",
  "look.square.kiosk": "Будката знае повече новини, отколкото продава.",
  "look.square.statue": "Паметник на местен герой от бюста нагоре. Отдолу бюджетът е свършил.",
  "look.square.old_men_bench": "Пейката е единствената социология с постоянна извадка.",
  "look.square.election_notice": "Пише, че изборите са прозрачни. Хартията обаче е леко мътна.",
  "look.square.mehana_menu": "Менюто е ламинирано, за да не попиват цените.",
  "look.dropped_items": "Торбата пази {count} изоставени решения. За разлика от Бай Митко, тя не губи нищо.",
  "look.mehana.oil": "Олио. В тази държава и салатата, и кариерата се плъзгат по него.",
  "look.mehana.water_jug": "Вода. Най-опасната течност в механата, защото буди съмнения.",
  "look.mehana.table": "Бай Митко е седнал с увереността на човек, чиято сметка ще я плаща следващото управление.",
  "look.mehana.bai_mitko_rakia_glass": "Точно тази чаша Тони наблюдава като изборна комисия с лично отношение.",
  "look.mehana.tony_rakia_glass": "Ракия до ръба. При Тони прозрачността винаги е с висок градус.",
  "look.npc.mehana_waiter": "Киро помни всяка поръчка и забравя всяка молба за касова бележка.",
  "look.npc.baba_stoyanka": "Баба Стоянка гледа като човек, който е преживял три режима и четири ремонта на площада.",
  "look.npc.tony_fridge": "Тони Хладилника. Човек с гръб като секция и черен дроб като общински бюджет.",

  "msg.walk": "Бай Митко тръгва с походка на човек, който дължи пари в три посоки.",
  "msg.no_use": "Морално спорно, административно невъзможно.",
  "msg.taken": "Взето. Това изглежда полезно, или поне отричаемо.",
  "msg.already_taken": "Вече е прибрано. Бай Митко не повтаря кражба без причина.",
  "msg.inventory.dropped_nearby": "Бай Митко остави {item} наблизо. Ако потрябва, ще си го прибере.",
  "msg.inventory.picked_up_again": "{item} отново е в джобовете на Бай Митко.",
  "msg.inventory.cannot_use_with": "{item} няма работа върху {target}.",
  "msg.inventory.cannot_combine": "{item} и {target} отказват да влязат в коалиция.",
  "msg.inventory.cannot_use_on_self": "Бай Митко не намира лично приложение за {item}.",
  "msg.need_talk": "Това не е разговор, това е инфраструктура.",
  "msg.scene_saved": "Запазено.",
  "msg.mehana.rakia_ordered": "Ракийката пристига. Чашата е малка, но мандатът й е силен.",
  "msg.rakia.level.daisy": "За здраве. И за кворум.",
  "msg.rakia.level.merry": "Ей сега вече платформата ми стана по-широка.",
  "msg.rakia.level.tipsy": "Аз не залитам. Коалицията мести пода.",
  "msg.rakia.level.plastered": "Тихо! Водя преговори с гардероба.",
  "msg.water_recovery": "Водата не прави чудеса, но Бай Митко поне си спомни кой под е неговият.",
  "msg.self.water": "Бай Митко изпи водата. Светът загуби един градус и половин аргумент.",
  "msg.self.tripe_soup": "Шкембето свали два градуса от Бай Митко и три слоя боя от буркана.",
  "msg.self.shopska": "Шопската пое част от алкохола. Сиренето поиска заслугата.",
  "msg.self.rakia": "Бай Митко изпи бутилката служебно. Кампанията веднага стана по-убедителна от пода.",
  "msg.self.village_wine": "Селското вино добави един градус и далечен спомен за читалищна забава.",
  "msg.self.accordion": "Бай Митко изсвири старата мелодия на себе си. Спомените се върнаха, но парите — не.",
  "msg.self.sunflower_oil": "Бай Митко изпи олиото. Вътрешната му политика вече се движи без триене.",
  "msg.mehana.tripe_soup": "Шкембето пристигна като топла парламентарна комисия. Бай Митко се събра с няколко процента.",
  "msg.mehana.shopska_ordered": "Шопската идва под убедително мнозинство от сирене. Доматите искат наблюдатели.",
  "msg.mehana.rakia_to_go": "Киро уви ракията за из път. Така юридически я превърна от питие в багаж.",
  "msg.mehana.shopska_to_go": "Киро затвори шопската в кутия. Сиренето вече пътува служебно.",
  "msg.mehana.tripe_soup_to_go": "Шкембето влиза в буркан. Миризмата отказва да подпише приемо-предавателния протокол.",
  "msg.mehana.village_wine": "Киро налива от селското. Виното има послевкус на бъчва, избори и далечен братовчед.",
  "msg.mehana.village_wine_to_go": "Киро подава бутилката без етикет. Така съдържанието остава политически независимо.",
  "msg.oil_used": "Бай Митко изпи олиото с изражение на човек, който инвестира в бъдещето.",
  "msg.accordion_tony": "Тони затвори очи и запя втория глас. Споменът за една сервитьорка от 1998-а временно прекрати надзора над чашата.",
  "msg.accordion_baba_before_vote": "Баба Стоянка: Върна ме на една селска забава, когато коленете ми още имаха кворум. Хубаво свириш, ама за гласа донеси нещо, което влиза в тенджерата.",
  "msg.accordion_baba_after_vote": "Баба Стоянка: Свири сега. Гласът вече ти го дадох, но младостта още ми дължи едно хоро.",
  "msg.accordion_kiro": "Киро: Ако продължиш, ще го пиша музика на живо. Ако спреш — такса спокойствие.",
  "msg.accordion_animal": "Животното изслуша мелодията, наклони глава и отказа да разкрие политическите си предпочитания.",
  "msg.accordion_generic_npc": "Старата мелодия намери нечий спомен. Човекът отказа да уточни годината и семейното положение.",
  "msg.water_swap_ready": "Докато Тони пееше, Бай Митко подмени ракията в своята чаша с вода. Надзорът временно беше музикален.",
  "msg.water_swap_watched": "Тони: Вода в твоята чаша? Още не си разсеял надзорния орган.",
  "msg.water_swap_still_watched": "Тони още гледа чашата. Повторението не прави номера по-законен.",
  "msg.water_tony_wrong_glass": "Това е чашата на Тони. Подмяната на противниковата ракия е от друг наказателен състав.",
  "msg.tony.gift_not_vote": "Тони: Почерпка приемам след вота. Преди вота се води опит за влияние, а аз държа опитът да е алкохолен и равнопоставен.",
  "msg.kiro.return_purchase": "Киро: Да ми върнеш купеното се води обратна доставка. Трябва нова касова бележка и по-голяма сметка.",
  "msg.scene_not_ready": "Тази част от общината още е в ремонт на ремонта.",

  "quest.chapter1.main.title": "Спечели селските избори, преди кредиторите да те намерят.",
  "quest.chapter1.fake_diploma.title": "Направи диплома, достатъчно впечатляваща за избиратели, които не четат дипломи.",
  "quest.chapter1.baba_vote.title": "Убеди баба Стоянка, че твоята корупция поне е традиционна.",
  "quest.chapter1.tony_vote.title": "Спечели подкрепата на Тони Хладилника, без да изпаднеш в безсъзнание.",
  "quest.chapter1.tony_vote.stage.accept_challenge": "Приеми алкохолното предизвикателство на Тони Хладилника.",
  "quest.chapter1.tony_vote.stage.distract": "Намери начин да разсееш Тони по време на предизвикателството.",
  "quest.chapter1.tony_vote.stage.swap_water": "Подмени ракията в чашата на Бай Митко с вода.",
  "quest.chapter1.tony_vote.stage.finish_challenge": "Довърши алкохолното предизвикателство на Тони.",
  "quest.chapter1.journalist.title": "Оцелей пред въпросите на журналиста, без случайно да кажеш истината.",
  "quest.chapter1.ballot_box.title": "Намери изчезналата урна, преди някой да ферментира демокрацията.",

  "dialogue.common.back": "Назад.",
  "dialogue.square.mehana_menu.title": "МЕХАНА „ДВЕТЕ КОЗИ“ — ДНЕШНО МЕНЮ",
  "dialogue.square.mehana_menu.food_heading": "ЯСТИЯ",
  "dialogue.square.mehana_menu.meatballs": "Кюфтета по обществена поръчка — две по документи, едно в чинията.",
  "dialogue.square.mehana_menu.shopska": "Шопска „Пълна прозрачност“ — всичко е покрито със сирене.",
  "dialogue.square.mehana_menu.mash": "Пюре „Ремонт на ремонта“ — вчерашното, но с прясна кръпка.",
  "dialogue.square.mehana_menu.drinks_heading": "НАПИТКИ",
  "dialogue.square.mehana_menu.rakia": "Ракия „Служебна“ — временна, докато стане постоянна.",
  "dialogue.square.mehana_menu.wine": "Вино „Добросъседско“ — оправя отношенията, не причините.",
  "dialogue.square.mehana_menu.beer": "Бира „Коалиционна“ — две бутилки в една чаша.",
  "dialogue.square.mehana_menu.water": "Вода „Без мнозинство“ — никой не я поръчва.",
  "dialogue.square.mehana_menu.close": "Затвори менюто",
  "dialogue.waiter.start": "Киро: Менюто е ориентировъчно. Сметката е окончателна.",
  "dialogue.waiter.choice.rakia": "Една ракия.",
  "dialogue.waiter.choice.shopska": "Една шопска салата.",
  "dialogue.waiter.choice.tripe_soup": "Едно шкембе за стабилизация.",
  "dialogue.waiter.choice.village_wine": "Бутилка от селското вино.",
  "dialogue.waiter.choice.tony_weakness": "Тони винаги ли гледа така чуждите чаши?",
  "dialogue.waiter.serving_question": "Киро: За тук или за вкъщи?",
  "dialogue.waiter.choice.for_here": "За тук. Да се консумира веднага.",
  "dialogue.waiter.choice.to_go": "За вкъщи. Опаковай го.",
  "dialogue.waiter.choice.people": "Кой друг пие тук?",
  "dialogue.waiter.choice.leave": "Само проверявам цените.",
  "dialogue.waiter.people": "Киро: Тони пие на голямата маса. Другите са временна коалиция около онзи, който плаща.",
  "dialogue.waiter.tony_weakness": "Киро: Само докато е буден. Засвири му стара сватбарска и затваря очи заради една Снежана от бюфета през 1998-а. Тогава и касата може да мине покрай него.",
  "dialogue.tony.start": "Тони: Говори. Чашата ми слуша.",
  "dialogue.tony.choice.challenge": "Да говорим за чашите.",
  "dialogue.tony.choice.challenge_status": "Защо гледаш моята чаша?",
  "dialogue.tony.choice.finish_challenge": "Да довършим доказването на капацитет.",
  "dialogue.tony.choice.confirm_support": "Значи гласът ти е за мен?",
  "dialogue.tony.choice.politics": "Тони, селото има нужда от стабилност.",
  "dialogue.tony.choice.leave": "Ще стабилизирам отвън.",
  "dialogue.tony.politics": "Тони: Стабилност има в хладилника. Отваряш - вътре пак е студено.",
  "dialogue.tony.challenge": "Тони: Две еднакви чаши. Пием по равно. Който се откаже, агитира за стария кмет. И ти гледам чашата — избори са, трябва да има контрол.",
  "dialogue.tony.choice.accept": "Приемам. Черният ми дроб е коалиционен.",
  "dialogue.tony.choice.refuse": "Още не. Трябва ми предизборна подготовка.",
  "dialogue.tony.challenge_accepted": "Тони: Киро, две ракии. Еднакви — да не се намесва демокрацията.",
  "dialogue.tony.challenge_deferred": "Тони: Върви се подготви. Аз не почвам вот без кворум и пиене без кандидат.",
  "dialogue.tony.choice.prepare": "Ще се върна с необходимия капацитет.",
  "dialogue.tony.challenge_waiting": "Тони: Гледам твоята. Моята си знае работата.",
  "dialogue.tony.contest_result": "Тони изпи своята. Бай Митко изпи водата с героично страдание. Тони: Издържа. Дроб ли е, процедура ли е — и двете стават за местната власт. Имаш гласа ми.",
  "dialogue.tony.support_confirmed": "Тони: Твой е. Не ме карай да повтарям — повторението е за пиене, не за политика.",
  "dialogue.baba.start": "Баба Стоянка: Всички сте маскари, ама някои поне поздравяват.",
  "dialogue.baba.choice.ask_vote": "Да поговорим за гласа ти.",
  "dialogue.baba.choice.tradition": "Моята корупция е традиционна.",
  "dialogue.baba.choice.promise": "Ще ремонтирам ремонта.",
  "dialogue.baba.choice.offer_bills": "Нося ти неплатени сметки. Народен документ.",
  "dialogue.baba.choice.offer_water": "Чаша вода. Чиста като намеренията ми.",
  "dialogue.baba.choice.offer_shopska": "Шопска салата. С много национална отговорност.",
  "dialogue.baba.choice.offer_tripe_soup": "Шкембе чорба. Възстановява доверието.",
  "dialogue.baba.choice.offer_rakia": "Бутилка ракия. За предизборно разбирателство.",
  "dialogue.baba.choice.offer_oil": "Бутилка олио. Традиционно и без програма.",
  "dialogue.baba.choice.offer_wine": "Бутилка вино. За възстановяване на отношенията.",
  "dialogue.baba.choice.confirm_vote": "Гласът ти още е за мен, нали?",
  "dialogue.baba.choice.leave": "Ще мина пак, ако не ме намерят.",
  "dialogue.baba.tradition": "Баба Стоянка: Традиционна, викаш? Значи поне ще оставиш нещо за децата.",
  "dialogue.baba.vote_terms": "Баба Стоянка: За моя глас първо донеси нещо полезно. Обещания за зимнина вече имам.",
  "dialogue.baba.promise": "Баба Стоянка: Ремонта го ремонтират откакто козата ми беше мома.",
  "dialogue.baba.vote_confirmed": "Баба Стоянка: За теб е. Не ме карай да повтарям — ще поскъпне.",
  "msg.baba.reject_bills": "Баба Стоянка: Моите са по-подредени. С чужд борч глас не се купува — само тревога.",
  "msg.baba.reject_water": "Баба Стоянка: Чешмата е на двайсет крачки. Ти и подкупа искаш общината да го плаща.",
  "msg.baba.reject_shopska": "Баба Стоянка: Без хляб, без ракия и вече топла. Това не е подкуп, а остатък.",
  "msg.baba.reject_tripe_soup": "Баба Стоянка: Студено шкембе се дава на враг, не на избирател.",
  "msg.baba.reject_rakia": "Баба Стоянка: Ракия ли? Аз моята си я варя. С купешка ракия можеш да купиш само главоболие.",
  "msg.baba.accept_oil": "Баба Стоянка: Е, това поне влиза в тенджерата. Ще гласувам за теб, но торбичката си я връщам.",
  "msg.baba.reject_late_oil": "Баба Стоянка: Преди три обиди щеше да мине. Сега олиото е само лихвата. Донеси бутилка вино — не за гласа, а за възстановяване на отношенията.",
  "msg.baba.reject_early_wine": "Баба Стоянка: Вино се носи за сдобряване. Ние още не сме се скарали както трябва. Донеси олио.",
  "msg.baba.accept_wine": "Баба Стоянка: Така вече говориш като човек, който е разбрал тарифата. Имаш гласа ми. За последен път до следващите избори."
};
