export const electionEn = {
  "election.start": "The Mayor: Before we count anything, I have three entirely spontaneous objections.",
  "election.ready": "The Mayor: My objections have been filed. Apparently that is different from being upheld.",
  "election.need_box": "The Mayor: An election without a box? At last, an innovation I can support. Bring it to the commission table.",
  "election.deliver": "Put the empty ballot box on the table.",
  "election.delivered": "Penka checks the empty box and seals it for voting. Nothing inside yet. A promising start.",
  "election.not_ready": "First finish registration and the interview. The commission needs the actual box, too.",
  "election.ask.credentials": "You object to my registration?",
  "election.ask.evidence": "You object to the expense record?",
  "election.ask.container": "You object to this box?",
  "election.objection.credentials": "The Mayor: That diploma is suspiciously official. Who authorized this?",
  "election.answer.credentials": "You stamped it. Penka registered it. Shall we inspect your handwriting?",
  "election.accepted.credentials": "The Mayor: My signature is authentic. Its enthusiasm was taken out of context.",
  "election.objection.evidence": "The Mayor: A receipt proves expenditure. It does not prove anyone was supposed to receive anything.",
  "election.answer.evidence": "The reporter checked the public expense record. It is already on file.",
  "election.accepted.evidence": "The reporter: Exactly. We have finished checking the receipt. Your explanation is still under construction.",
  "election.objection.container": "The Mayor: This container belongs in the archive. Democracy must not disrupt storage.",
  "election.answer.container": "A transparent seasonal container remains in its place. Penka can check the register.",
  "election.accepted.container": "Penka: The classification is satisfied. The pickles have not filed an objection.",
  "election.count": "Open voting and count the result.",
  "election.leave": "I still have people to see. Leave the count for later.",
  "election.continue": "Continue",
  "election.table_look": "Deliver the box here, settle the three objections, then open voting. Until the final count, I can still visit the village.",
  "election.mayor_look": "He has prepared a victory speech and three reasons not to count.",
  "election.reporter": "Registration, evidence, container. Answer his objections at the table. Support is earned outside this room.",
  "election.baba": "I came for the vote. The fountain can manage five minutes without supervision.",
  "election.tony": "I promised support. I even brought my sitting-down stamina.",
  "election.quest.archive": "Ask Penka about the archive and recover the ballot box.",
  "election.quest.interview": "Return to the square and finish the reporter’s interview.",
  "election.quest.deliver": "Bring the ballot box to the polling room’s commission table.",
  "election.quest.credentials": "At the polling table, answer the Mayor’s registration objection.",
  "election.quest.evidence": "Remind the Mayor that the reporter verified the expense record.",
  "election.quest.container": "Explain the archive’s transparent-container classification.",
  "election.quest.vote": "Finish any supporter business, then open voting at the commission table.",
  "election.reason.convincing_win": "Both supporters backed you, with strong influence, good public mood and low suspicion: a clear majority.",
  "election.reason.narrow_win": "Your backing carried the vote, but the campaign fell short of a clear majority. Both supporters together always secure a win.",
  "election.reason.loss": "Paperwork opened the election; it could not win it. You needed both supporters, or one supporter with at least 15 influence, 35 public mood and no more than 70 suspicion.",
  "election.report.baba_yes": "Baba Stoyanka kept her promise and brought her support.",
  "election.report.baba_no": "Baba Stoyanka’s support was not secured.",
  "election.report.tony_yes": "Tony backed you after the tavern challenge.",
  "election.report.tony_no": "Tony’s support was not secured.",
  "election.epilogue.mayor_win": "The outgoing Mayor offers Mitko the office keys. ‘The bottom drawer sticks. Consider that your first reform.’",
  "election.epilogue.mayor_loss": "The Mayor pockets the office keys. ‘The people have spoken. Penka, file what they meant.’ Mitko leaves as a citizen, with all the paperwork to prove it.",
  "election.epilogue.water": "Outside, the fountain keeps running. For once, a campaign promise has a maintenance problem instead of an excuse.",
  "election.epilogue.dry": "Outside, the fountain is still dry. The village has heard another speech; it is still waiting for water.",
  "election.epilogue.creditors": "Two familiar creditors wait by the door. ‘Congratulations on finishing. Now we can discuss what you owe.’ Mitko: ‘Could we at least form a committee?’"
};

export const electionBg = {
  "election.start": "Кметът: Преди да броим, имам три съвсем спонтанни възражения.",
  "election.ready": "Кметът: Възраженията ми са приети за сведение. Оказа се, че това не е победа.",
  "election.need_box": "Кметът: Избори без урна? Най-сетне разумна реформа. Донесете я на масата на комисията.",
  "election.deliver": "Слагам празната урна на масата.",
  "election.delivered": "Пенка проверява празната урна и я запечатва за гласуването. Засега вътре няма нищо. Добро начало.",
  "election.not_ready": "Първо регистрацията и интервюто. И урната трябва да е тук, не само по документи.",
  "election.ask.credentials": "Какво ѝ е на регистрацията ми?",
  "election.ask.evidence": "Какво ѝ е на разписката?",
  "election.ask.container": "Какво ѝ е на урната?",
  "election.objection.credentials": "Кметът: Тая диплома е съмнително редовна. Кой я е заверил?",
  "election.answer.credentials": "Вие я подпечатахте. Пенка ме вписа. Да сравняваме ли подписите?",
  "election.accepted.credentials": "Кметът: Подписът е мой. Но ентусиазмът му е изваден от контекста.",
  "election.objection.evidence": "Кметът: Разписката доказва разход. Не пише, че някой трябва да види полза.",
  "election.answer.evidence": "Журналистката провери общинския разход. Документът вече е при нея.",
  "election.accepted.evidence": "Журналистката: Точно така. Разписката е проверена. Обяснението ви още е в ремонт.",
  "election.objection.container": "Кметът: Тая урна е архивна! Няма демокрацията да ни разбърква инвентара.",
  "election.answer.container": "На мястото ѝ има прозрачен съд за сезонна употреба. Пенка да провери описа.",
  "election.accepted.container": "Пенка: Класификацията е спазена. От киселите краставички възражение няма.",
  "election.count": "Да гласуваме и да преброим резултата.",
  "election.leave": "Имам още хора за обикаляне. Броенето ще почака.",
  "election.continue": "Нататък",
  "election.table_look": "Тук оставям урната, отговарям на трите възражения и откриваме гласуването. Дотогава мога да се върна на мегдана.",
  "election.mayor_look": "Подготвил е победна реч и три причини да не броим.",
  "election.reporter": "Регистрация, разход, урна. Отговори му на масата. Подкрепата се печели навън.",
  "election.baba": "Дойдох да гласувам. Чешмата ще изкара пет минути без надзор.",
  "election.tony": "Обещал съм подкрепа. Даже седнал мога да я оказвам.",
  "election.quest.archive": "Питай Пенка за архива и прибери урната.",
  "election.quest.interview": "Върни се на мегдана и довърши интервюто с журналистката.",
  "election.quest.deliver": "Занеси урната на масата на комисията в избирателната секция.",
  "election.quest.credentials": "На масата в секцията отговори на възражението за регистрацията.",
  "election.quest.evidence": "Напомни на кмета, че журналистката е проверила разхода.",
  "election.quest.container": "Обясни архивната класификация за прозрачните съдове.",
  "election.quest.vote": "Довърши уговорките за подкрепа и открий гласуването на масата на комисията.",
  "election.reason.convincing_win": "И двамата те подкрепиха. Влиянието е силно, настроението — добро, подозренията — малко. Убедителна победа.",
  "election.reason.narrow_win": "Подкрепата стигна за победа, но кампанията не убеди всички. С Баба и Тони заедно победата е сигурна.",
  "election.reason.loss": "Документите те допуснаха до изборите, но не ги спечелиха. Трябват ти и двамата поддръжници или един с поне 15 влияние, 35 настроение и най-много 70 подозрение.",
  "election.report.baba_yes": "Баба Стоянка удържа на думата си и те подкрепи.",
  "election.report.baba_no": "Не спечели подкрепата на Баба Стоянка.",
  "election.report.tony_yes": "Тони те подкрепи след състезанието в механата.",
  "election.report.tony_no": "Не спечели подкрепата на Тони.",
  "election.epilogue.mayor_win": "Досегашният кмет подава ключовете на Митко. „Долното чекмедже заяжда. Ето ти първата реформа.“",
  "election.epilogue.mayor_loss": "Кметът прибира ключовете. „Народът се произнесе. Пенка, заведи какво е искал да каже.“ Митко си тръгва гражданин. Вече има и документи за това.",
  "election.epilogue.water": "Навън чешмата си тече. За пръв път едно обещание иска поддръжка, а не оправдание.",
  "election.epilogue.dry": "Навън чешмата още е суха. Селото изслуша още една реч. Водата пак я няма.",
  "election.epilogue.creditors": "До вратата чакат двама познати кредитори. „Честито, приключихте. Сега да видим нашето.“ Митко: „Не може ли първо една комисия?“"
};
