export const archiveEn = {
  "archive.title": "Municipal Archive",
  "archive.back": "Back to the clerk",
  "archive.handle": "Jammed drawer handle",
  "archive.ledger": "Storage ledger",
  "archive.replacement": "Official replacement container",
  "archive.registration_first": "Clerk: Registration first. The archive is for candidates, not potential candidates.",
  "archive.clerk_location": "Clerk: The ballot box is in the archive cabinet on the right, filed under ‘Transparent containers — seasonal use’.",
  "archive.clerk_strap": "Clerk: The drawer sticks. You need a strong strap around the handle. Your accordion has one, doesn’t it?",
  "archive.clerk_ledger": "Clerk: Read the storage ledger inside the drawer. It tells you what must remain.",
  "archive.clerk_replace": "Clerk: Leave another transparent container in the box’s place. We count containers. Contents are another department.",
  "archive.clerk_take": "Clerk: The replacement is in place. You may take the empty ballot box.",
  "archive.finished": "The ballot box is accounted for. Next, finish the journalist’s interview in the square and bring the box to the election commission.",
  "archive.jammed": "The handle holds, but the drawer is jammed. A strong strap would give me a better grip. The accordion has one.",
  "archive.inspect_first": "I should look at the handle before pulling it with anything.",
  "archive.opened": "The accordion strap pulls the drawer free. I unhook it and keep the accordion. Finally, an instrument of government that works.",
  "archive.ledger_text": ["Storage rule: ‘One transparent container for seasonal use must remain in the ballot-box position. Equivalent replacement permitted.’", "A pickle jar is transparent. Pickles have a season. For once, I meet all the requirements."],
  "archive.jar_look": "A jar of pickles. Transparent, seasonal and already in public service.",
  "archive.box_look": "An empty ballot box. No votes, no pickles. There’s still time for both to disappoint us.",
  "archive.read_first": "There’s a storage ledger beside it. I should read the release rules first.",
  "archive.replacement_first": "The ledger requires a transparent seasonal container here. I can put the pickle jar in the box’s place.",
  "archive.exchanged": "I put the jar in the designated storage position. One transparent seasonal container remains. The box can now leave.",
  "archive.recovered": "An empty ballot box, properly released. Now for the journalist’s questions in the square.",
  "archive.replacement_look": "The jar now fulfils the archive’s container quota.",
  "archive.leave_jar": "That jar is the replacement. Taking it back would undo the paperwork.",
  "archive.drop_outside": "I’ll step away from the drawer before putting anything down.",
  "archive.cellar_retired": "Kiro’s cellar is for tavern supplies. The ballot box belongs in the municipal archive.",
  "archive.quest.find": "Inspect the archive cabinet on the right of the municipality.",
  "archive.quest.read": "Read the storage ledger inside the open drawer.",
  "archive.quest.replace": "Take the pickle jar and use it on the ballot box to leave a replacement.",
  "archive.quest.take": "Take the empty ballot box."
};
export const archiveBg = {
  "archive.title": "Общински архив",
  "archive.back": "Обратно при Пенка",
  "archive.handle": "Дръжка на заялото чекмедже",
  "archive.ledger": "Складова книга",
  "archive.replacement": "Заместващ съд по опис",
  "archive.registration_first": "Пенка: Първо регистрацията. Архивът е за кандидати, не за кандидат-кандидати.",
  "archive.clerk_location": "Пенка: Урната е в архивния шкаф вдясно. Води се на „Прозрачни съдове за сезонна употреба“.",
  "archive.clerk_strap": "Пенка: Чекмеджето заяжда. Трябва здрава каишка за дръжката. Акордеонът ти няма ли?",
  "archive.clerk_ledger": "Пенка: Прочети складовата книга в чекмеджето. Там пише какво трябва да остане.",
  "archive.clerk_replace": "Пенка: Остави друг прозрачен съд на мястото на урната. Ние броим съдовете. Съдържанието е към друг отдел.",
  "archive.clerk_take": "Пенка: Заместващият съд е на място. Можеш да вземеш празната урна.",
  "archive.finished": "Урната е уредена. Остава интервюто с журналистката на площада, после носим урната на избирателната комисия.",
  "archive.jammed": "Дръжката държи, ама чекмеджето е заяло. Със здрава каишка ще го дръпна по-добре. Акордеонът има.",
  "archive.inspect_first": "Я първо да огледам дръжката, преди да я дърпам с каквото ми падне.",
  "archive.opened": "Дръпнах с каишката и чекмеджето поддаде. Откачам я и си прибирам акордеона. Най-после работещ инструмент на властта.",
  "archive.ledger_text": ["Ред за съхранение: „На мястото на урната задължително остава един прозрачен съд за сезонна употреба. Допуска се равностойна замяна.“", "Бурканът е прозрачен. Туршията е сезонна. За пръв път отговарям на всички условия."],
  "archive.jar_look": "Буркан с туршия. Прозрачен, сезонен и вече на държавна служба.",
  "archive.box_look": "Празна урна. Ни бюлетини, ни туршия. Още никой не я е разочаровал.",
  "archive.read_first": "До нея има складова книга. Първо да видя как се отпуска имущество.",
  "archive.replacement_first": "По опис тук трябва да остане прозрачен сезонен съд. Мога да сложа буркана на мястото на урната.",
  "archive.exchanged": "Оставям буркана на определеното място. Един прозрачен сезонен съд е наличен. Урната вече може да напусне.",
  "archive.recovered": "Празна урна, отпусната по надлежния ред. Сега при журналистката на площада.",
  "archive.replacement_look": "Бурканът вече покрива бройката по опис.",
  "archive.leave_jar": "Този буркан замества урната. Ако си го прибера, пак ще излезе липса.",
  "archive.drop_outside": "Първо ще се отдръпна от чекмеджето, после ще оставям багаж.",
  "archive.cellar_retired": "Мазето на Киро е за запасите на механата. Урната е работа на общинския архив.",
  "archive.quest.find": "Огледай архивния шкаф вдясно в общината.",
  "archive.quest.read": "Прочети складовата книга в отвореното чекмедже.",
  "archive.quest.replace": "Вземи буркана и го използвай върху урната, за да оставиш заместител.",
  "archive.quest.take": "Вземи празната изборна урна."
};
