export const registrationEn = {
  "registration.receipt_obtained": "A municipal receipt: the Mayor’s tavern bill, filed as fountain maintenance. I should show this to the journalist.",
  "registration.receipt_handover": "Journalist: So the fountain was serviced by the glass. I’ll take the receipt to the Mayor’s office. Meet me there with your diploma; let the clerk check it first.",
  "registration.stamped": "The Mayor stamps the whole stack. Journalist: Including Mitko’s diploma. Very thorough. Mitko: I’ll take that to the clerk before the ink changes its mind.",
  "registration.registered": "Clerk: Diploma validated by the Mayor. You’re registered. Now we need the ballot box. It is in the archive cabinet on the right, under ‘Transparent containers — seasonal use’.",
  "registration.already_registered": "Clerk: You’re already registered. The ballot box is in the archive cabinet on the right, under ‘Transparent containers — seasonal use’.",
  "registration.clerk_rejects": "Clerk: The diploma needs the Mayor’s stamp. Show the journalist the municipal expense receipt from the mehana, then take your diploma to his office. Bring it back to me after validation.",
  "registration.clerk_start": "Clerk: Candidate registration. Diploma first, official validation second. Smiling is optional.",
  "registration.present": "Please check my diploma.",
  "registration.status": "Am I registered?",
  "registration.need": "What is still missing?",
  "registration.leave": "I’ll be back.",
  "registration.mayor_start": "Mayor: Everything in this office is in order. Even the queue for putting things in order.",
  "registration.confront": "We have a question about the fountain expenses.",
  "registration.next": "What happens next?",
  "registration.mayor_requirements": "Bring the diploma the clerk checked. The journalist must have the expense receipt and be here to ask her questions.",
  "registration.mayor_evidence": "Journalist: This receipt lists tavern drinks as fountain maintenance. Mayor: Public water requires public consultation. Consultation makes people thirsty.",
  "registration.listen": "Let him explain.",
  "registration.mayor_offer": "Mayor: Mitko, there’s a small post for you. Assistant to the assistant. A chair, eventually. No need to stand against me.",
  "registration.stay_candidate": "I’m staying in the election. Here is my diploma.",
  "registration.mayor_stack": "The Mayor puts the diploma among his expense papers. Mayor: Every document leaving my office is properly validated. Watch.",
  "registration.watch_stamp": "Watch him stamp the stack.",
  "registration.collect_receipt": "What is that receipt under the glass?",
  "registration.kiro_receipt": "The journalist needs the municipal expense record.",
  "registration.tony_result": "Tony: You held your drink. You’ve got my support. There’s a municipal receipt under that glass, if you’re collecting paperwork too.",
  "registration.journalist_start": "Journalist: A new candidate. I’m collecting evidence, not another pile of promises.",
  "registration.give_receipt": "Here is the municipal receipt.",
  "registration.ask_evidence": "What evidence do you need?",
  "registration.evidence_request": "Journalist: The mehana has a receipt for the Mayor’s expenses, charged to fountain maintenance. Tony has it at his table. If he won’t help, ask Kiro for the record.",
  "registration.reporter_next": "Your diploma goes to the clerk after the Mayor validates it. Once you’ve recovered the ballot box, come back for the final interview.",
  "registration.guard_blocked": "Guard: Candidates only. Put your campaign material on the board beside the kiosk first, so we know who you are.",
  "registration.office_blocked": "The Mayor is not receiving candidates alone. Give the journalist the mehana expense receipt; she’ll arrange the meeting.",
  "registration.seal_prop": "An official seal. Taking it will not register me; the Mayor must validate my diploma.",
  "registration.no_self_stamp": "My own stamping does not count. The Mayor validates the diploma; the clerk registers me.",
  "registration.use_clerk": "Give the validated diploma to the clerk. She keeps the register.",
  "registration.talk_mayor": "Talk to the Mayor with the journalist present to raise the expense receipt and present the diploma.",
  "registration.quest.evidence": "Meet the journalist by the kiosk. Obtain the municipal receipt from Tony or ask Kiro after she requests evidence.",
  "registration.quest.clerk": "Take your diploma to the municipality clerk for inspection. Retrieve it first if you dropped it.",
  "registration.quest.mayor": "Bring your diploma to the Mayor’s office. The journalist is waiting there with the receipt. Talk to the Mayor.",
  "registration.quest.register": "Return the Mayor-validated diploma to the clerk to complete registration.",
  "registration.office_reporter": "Journalist: I have the receipt. Bring the checked diploma and talk to the Mayor. I want his explanation on the record."
};

export const registrationBg = {
  "registration.receipt_obtained": "Общинска касова бележка: сметката на кмета в механата, отчетена като поддръжка на фонтана. Трябва да я покажа на журналистката.",
  "registration.receipt_handover": "Журналистката: Значи фонтанът е обслужван на чашка. Вземам бележката и отивам в кабинета на кмета. Ела с дипломата; първо я покажи на деловодителката.",
  "registration.stamped": "Кметът подпечатва цялата купчина. Журналистката: Включително дипломата на Митко. Много старателно. Митко: Отивам при деловодителката, преди мастилото да си промени мнението.",
  "registration.registered": "Пенка: Дипломата е заверена от кмета. Регистриран си. Сега урната: в архивния шкаф вдясно, при прозрачните съдове за сезонна употреба.",
  "registration.already_registered": "Пенка: Вече си регистриран. Урната е в архивния шкаф вдясно, при прозрачните съдове за сезонна употреба.",
  "registration.clerk_rejects": "Деловодителката: На дипломата ѝ трябва кметски печат. Покажи на журналистката общинската бележка от механата, после занеси дипломата в кабинета му. След заверката я върни при мен.",
  "registration.clerk_start": "Деловодителката: Регистрация на кандидати. Първо дипломата, после заверката. Усмивката не е задължителна.",
  "registration.present": "Моля да проверите дипломата ми.",
  "registration.status": "Регистриран ли съм?",
  "registration.need": "Какво още липсва?",
  "registration.leave": "Ще се върна.",
  "registration.mayor_start": "Кметът: В този кабинет всичко е наред. Даже опашката за оправяне на нередностите.",
  "registration.confront": "Имаме въпрос за разходите по фонтана.",
  "registration.next": "Какво следва?",
  "registration.mayor_requirements": "Донеси дипломата, която деловодителката провери. Журналистката трябва да е тук с бележката, за да зададе въпросите си.",
  "registration.mayor_evidence": "Журналистката: Тук почерпката в механата е отчетена като поддръжка на фонтана. Кметът: Обществената вода изисква обществено обсъждане. От обсъждане се ожаднява.",
  "registration.listen": "Да чуем обяснението.",
  "registration.mayor_offer": "Кметът: Митко, имам една длъжност за теб. Помощник на помощника. След време — и стол. Защо ще се явяваш срещу мен?",
  "registration.stay_candidate": "Оставам кандидат. Ето дипломата ми.",
  "registration.mayor_stack": "Кметът слага дипломата при разходните документи. Кметът: Всеки документ, излязъл от кабинета ми, е надлежно заверен. Гледайте.",
  "registration.watch_stamp": "Изчаквам да подпечатва купчината.",
  "registration.collect_receipt": "Каква е тази бележка под чашата?",
  "registration.kiro_receipt": "Журналистката търси документа за общинските разходи.",
  "registration.tony_result": "Тони: Издържа. Имаш подкрепата ми. Под чашата има и една общинска бележка, ако събираш и документи.",
  "registration.journalist_start": "Журналистката: Нов кандидат. Събирам доказателства, не още една купчина обещания.",
  "registration.give_receipt": "Ето общинската касова бележка.",
  "registration.ask_evidence": "Какви доказателства ти трябват?",
  "registration.evidence_request": "Журналистката: В механата има бележка за разходите на кмета, отчетени като поддръжка на фонтана. Тони я държи на масата. Ако не помогне, поискай документа от Киро.",
  "registration.reporter_next": "След кметската заверка занеси дипломата на деловодителката. Като намериш урната, ела за последното интервю.",
  "registration.guard_blocked": "Охраната: Само кандидати. Първо залепи листовките на таблото до будката, да знаем кой си.",
  "registration.office_blocked": "Кметът не приема кандидати насаме. Дай на журналистката бележката от механата; тя ще уреди срещата.",
  "registration.seal_prop": "Служебен печат. Вземането му няма да ме регистрира; кметът трябва да завери дипломата.",
  "registration.no_self_stamp": "Сам да си бия печат не се брои. Кметът заверява дипломата, деловодителката ме регистрира.",
  "registration.use_clerk": "Заверената диплома се дава на деловодителката. Тя води регистъра.",
  "registration.talk_mayor": "Трябва да поговоря с кмета пред журналистката за бележката и да представя дипломата.",
  "registration.quest.evidence": "Потърси журналистката до будката. Вземи бележката от Тони или я поискай от Киро, след като тя поиска доказателства.",
  "registration.quest.clerk": "Покажи дипломата на деловодителката в общината. Ако си я оставил някъде, първо я прибери.",
  "registration.quest.mayor": "Занеси дипломата в кабинета на кмета. Журналистката чака там с бележката. Говори с кмета.",
  "registration.quest.register": "Върни заверената от кмета диплома на деловодителката, за да те регистрира.",
  "registration.office_reporter": "Журналистката: Бележката е у мен. Донеси проверената диплома и говори с кмета. Искам официалното му обяснение."
};
