// Authored Bulgarian and adapted English; each entry is a single reaction.
const reactions = [
  ['msg.self.accordion.2',
    'Ето. Пръстите още помнят работа. Да не чуят кредиторите.',
    'My fingers still remember honest work. Keep that from the creditors.'],
  ['msg.self.accordion.3',
    'Поне тука като натисна правилното копче, нещо става.',
    'At least these buttons do something when I press them.'],
  ['msg.accordion_baba_before_vote.2',
    'Свириш хубаво, Митко. Ама с хоро празна стомна не се пълни.',
    'Lovely playing, Mitko. Now try filling a water jug with a dance tune.'],
  ['msg.accordion_baba_before_vote.3',
    'Моят така сменяше темата, като стане дума за работа. Кранът още чака.',
    'My husband played that whenever there was work to do. The valve is still waiting.'],
  ['msg.accordion_baba_after_vote.2',
    'Тая я свириха на сватбата ми. Мъжът се изтърка, песента държи.',
    'They played that at my wedding. The husband wore out. The tune held up.'],
  ['msg.accordion_baba_after_vote.3',
    'По-бавно, че си спомних кого трябваше да взема вместо дядо ти.',
    'Slower. I just remembered who I should have married instead.'],
  ['msg.accordion.tony',
    'Не плача. Хладилникът се размразява.',
    "I'm not crying. The Fridge is defrosting."],
  ['msg.accordion.tony.2',
    'Тая я знам. Припевът е „Наздраве“, другото е за оркестъра.',
    'I know this one. The chorus is “Cheers.” The band handles the rest.'],
  ['msg.accordion.tony.3',
    'По-силно, Митко. Да не чувам как ми свършва ракията.',
    "Louder, Mitko. I can hear my rakia running out."],
  ['msg.accordion_tony.2',
    'Тони затваря очи и запява. За пръв път чашата му остава без охрана.',
    'Tony shuts his eyes and sings. For once, his glass has no security detail.'],
  ['msg.accordion_tony.3',
    'Тони затваря очи: „На тая се запознах с една жена. Или с две. Свири!“',
    'Tony closes his eyes. “I met a woman to this tune. Possibly two. Keep playing!”'],
  ['msg.accordion_kiro.2',
    'За музиката — браво. За празната маса — поръчка.',
    'Lovely music. Now give that empty table something to do. Order.'],
  ['msg.accordion_kiro.3',
    'Бакшишите са в чинийката. Не в твоята — в моята.',
    'Tips go in the dish. Yours is the other dish. The empty one.'],
  ['msg.accordion.journalist',
    'Записвам: кандидатът най-после има програма. Засега — музикална.',
    'At last, a candidate with a programme. So far, strictly musical.'],
  ['msg.accordion.journalist.2',
    'Хубаво соло. Сега същото, но с отговор на въпроса.',
    'Lovely solo. Now try it again with an answer in it.'],
  ['msg.accordion.journalist.3',
    'Акордеонът поне се свива, като го притиснат. Вие само разтягате.',
    'Your accordion gets shorter under pressure. Your answers get longer.'],
  ['msg.accordion.old_men',
    'Единият: „На тая поведох хорото.“ Другият: „Към бюфета. Помним.“',
    'One: “I led the dance to this.” The other: “Straight to the bar. We remember.”'],
  ['msg.accordion.old_men.2',
    'Единият: „Едно време имаше музика!“ Другият: „И ти пак мрънкаше.“',
    'One: “We had proper music in our day!” The other: “You complained then, too.”'],
  ['msg.accordion.old_men.3',
    'Единият: „Да станем?“ Другият: „Първо да гласуваме. Аз съм против.“',
    'One: “Shall we get up?” The other: “Put it to a vote. I vote no.”'],
  ['msg.accordion.old_men.4',
    'Единият: „Фонтанът и той щял да пее.“ Другият: „Първо да му назначат диригент.“',
    'One: “They say the fountain will sing.” The other: “Once they appoint a conductor.”'],
  ['msg.accordion.kiosk',
    'Дочева: Митко, не ми разклащай вестниците. И без това заглавията едва се държат.',
    'Docheva: Easy, Mitko. Those headlines are barely holding together as it is.'],
  ['msg.accordion.kiosk.2',
    'Дочева: Дребни нямам. Ако свириш още, ще ти върна ресто с вчерашни новини.',
    "Docheva: No small change. Keep playing and you'll get yesterday's news instead."],
  ['msg.accordion.kiosk.3',
    'Дочева: Поръчки приемаш ли? Моята е да ми платиш вересията.',
    'Docheva: Taking requests? Mine is for you to settle your tab.'],
  ['msg.accordion.mayor',
    'Чудесно. Застани до мен, да изглежда, че аз съм го организирал.',
    'Excellent. Stand beside me so it looks like I arranged this.'],
  ['msg.accordion.mayor.2',
    'Такъв разтегателен инструмент ни трябва и за бюджета.',
    'We need an instrument like that for the budget. Something that stretches.'],
  ['msg.accordion.mayor.3',
    'За бис ще трябва ново откриване. Лентата ни е за еднократна употреба.',
    'An encore needs another opening ceremony. We only brought one ribbon.'],
  ['msg.accordion.clerk',
    'Мелодията я чух. Сега я подайте в два екземпляра.',
    'I heard the tune. Now submit it in duplicate.'],
  ['msg.accordion.clerk.2',
    'Тия паузи не са заверени. Някой може да допише куплет.',
    'Those pauses need a stamp. Someone could slip another verse in.'],
  ['msg.accordion.clerk.3',
    'Не мога да приема устна молба, дори да е с басов съпровод.',
    'Verbal applications are not accepted. Even with bass accompaniment.'],
  ['msg.accordion.colleague',
    'Аз само подпомагам колежката. Ритмичното кимане е нейна компетентност.',
    "I'm only assisting my colleague. Rhythmic nodding is her department."],
  ['msg.accordion.colleague.2',
    'Не съм спрял работа. Изчаквам да установя такта.',
    "I'm not avoiding work. I'm waiting to establish the beat."],
  ['msg.accordion.colleague.3',
    'Това можех и аз да го изсвиря. Ама нямам възложено.',
    "I could have played that. But I haven't been assigned to."],
  ['msg.accordion.background_clerk',
    'По-тихо. Броя листовете, а ти все ми вкарваш още една осмина.',
    "Quiet. I'm counting pages, and you keep adding an eighth."],
  ['msg.accordion.background_clerk.2',
    'Не съм се унесла. Проверявам дали тишината между нотите е служебна.',
    "I'm not daydreaming. I'm checking whether those rests count as office hours."],
  ['msg.accordion.background_clerk.3',
    'Може да оставите песента. Ще я изслушам, като свърша с входящите.',
    "Leave the tune here. I'll listen once I've cleared the incoming mail."],
  ['msg.accordion.security',
    'Акордеонът да остане отворен. Проверявам какво има между гънките.',
    'Keep that accordion open. I need to inspect between the folds.'],
  ['msg.accordion.security.2',
    'Това събиране разрешено ли е? Двамата с акордеона вече сте група.',
    'Is this gathering authorised? You and the accordion count as a group.'],
  ['msg.accordion.security.3',
    'Лична карта. На музиканта. Инструментът поне си има ремъци.',
    'Identification. Yours. The instrument is already securely strapped in.'],
  ['msg.accordion_animal.2',
    'Животното чака края. Вероятно смята, че след номера следва храна.',
    'The animal waits for the finale. It seems to expect a treat after the trick.'],
  ['msg.accordion_animal.3',
    'Животното мести едното ухо. За тази публика това е бис.',
    'One ear moves. From this audience, that counts as an encore.'],
  ['msg.accordion_generic_npc.2',
    'Хубава песен. Само не я обещавай в предизборната програма, че ще спреш по средата.',
    "Nice tune. Keep it out of your election promises or you'll never finish it."],
  ['msg.accordion_generic_npc.3',
    'Поне това обещание има край, който се чува.',
    "At least that's one promise with an ending we can hear."]
];

export const accordionBg = Object.fromEntries(reactions.map(([key, bg]) => [key, bg]));
export const accordionEn = Object.fromEntries(reactions.map(([key, , en]) => [key, en]));
