export const en = {
  "game.title": "Comrade Candidate",
  "chapter1.title": "Election Day in the Village",
  "scene.chapter1.apartment.title": "Bai Mitko's Apartment",
  "scene.chapter1.village_square.title": "Village Square",
  "scene.chapter1.mehana.title": "Mehana \"The Two Goats\"",

  "ui.new_game": "New Game",
  "ui.continue": "Continue",
  "ui.language": "Language",
  "ui.pause": "Pause",
  "ui.resume": "Resume",
  "ui.save": "Save",
  "ui.menu": "Menu",
  "ui.restart": "Restart",
  "ui.main_menu": "Main Menu",
  "ui.restart_confirm": "Restart Chapter 1 and clear the current save?",
  "ui.reset": "Reset",
  "ui.reset_confirm": "Reset the current game, pockets, and all saved inventory items?",
  "ui.quests": "Quests",
  "ui.hud": "Game status",
  "ui.inventory": "Inventory",
  "ui.verb": "Verb",
  "ui.meter.influence": "Influence",
  "ui.meter.rakia": "Rakia glasses",
  "ui.intoxication.daisy": "Daisy",
  "ui.intoxication.merry": "Merry",
  "ui.intoxication.tipsy": "Tipsy",
  "ui.intoxication.plastered": "Plastered",
  "ui.meter.suspicion": "Suspicion",
  "ui.meter.public_mood": "Public Mood",
  "ui.hint": "Left click: act. Right click: change verb. Esc: pause.",
  "npc.bai_mitko.name": "Bai Mitko",

  "verb.look": "Look",
  "verb.talk": "Talk",
  "verb.use": "Use",
  "verb.take": "Take",

  "exit.to_village_square": "To Village Square",
  "exit.to_apartment": "To Apartment",
  "exit.to_mehana": "To Mehana",
  "exit.to_municipality": "To Municipality",

  "item.accordion.name": "Accordion",
  "item.accordion.desc": "The only thing Bai Mitko ever played honestly.",
  "item.unpaid_bills.name": "Unpaid Bills",
  "item.unpaid_bills.desc": "A financial autobiography with a tragic ending.",
  "msg.apartment.unpaid_bills_taken": "The bills are pocketed. Evidence does not stay on the table unless guests are coming.",
  "item.empty_envelope.name": "Empty Envelope",
  "item.empty_envelope.desc": "Empty, but administratively promising.",
  "item.fake_diploma.name": "Fake Diploma",
  "item.fake_diploma.desc": "Official enough for voters who squint.",
  "item.rakia.name": "Bottle of Rakia",
  "item.rakia.desc": "High-proof liquid democracy.",
  "item.shopska_salad.name": "Shopska Salad",
  "item.shopska_salad.desc": "Tomatoes, cucumbers, and enough grated cheese to conceal the fiscal policy.",
  "item.sunflower_oil.name": "Sunflower Oil",
  "item.sunflower_oil.desc": "Folk medicine for heavy political decisions.",
  "item.glass_of_water.name": "Glass of Water",
  "item.glass_of_water.desc": "Colorless, nonpartisan, and suspiciously sober.",
  "item.campaign_pamphlets.name": "Campaign Pamphlets",
  "item.campaign_pamphlets.desc": "Promises on thin paper.",
  "item.suspicious_receipt.name": "Suspicious Receipt",
  "item.suspicious_receipt.desc": "It says receipt. It smells like evidence.",
  "item.pickle_jar.name": "Pickle Jar",
  "item.pickle_jar.desc": "A preserved vegetable with a clearer platform than most candidates.",
  "item.ballot_box.name": "Ballot Box",
  "item.ballot_box.desc": "Transparent by law, cloudy by tradition.",
  "item.municipality_stamp.name": "Municipality Stamp",
  "item.municipality_stamp.desc": "A little stamp can open a big door.",

  "hotspot.wallpaper.name": "Peeling Wallpaper",
  "hotspot.window.name": "Window",
  "hotspot.campaign_poster.name": "Campaign Poster Draft",
  "hotspot.mirror.name": "Cracked Mirror",
  "hotspot.tv.name": "Old TV",
  "hotspot.wardrobe.name": "Wardrobe",
  "hotspot.table.name": "Cheap Table",
  "hotspot.poster_board.name": "Campaign Board",
  "hotspot.fountain.name": "Fountain",
  "hotspot.kiosk.name": "News Kiosk",
  "hotspot.statue.name": "Statue",
  "hotspot.old_men_bench.name": "Old Men Bench",
  "hotspot.election_notice.name": "Election Notice",
  "hotspot.water_jug.name": "Water Jug",
  "hotspot.mehana_table.name": "Mehana Table",
  "hotspot.apartment.rakia_bottle.name": "Rakia Bottle",
  "hotspot.apartment.bed.name": "Sofa-bed",

  "npc.baba_stoyanka.name": "Baba Stoyanka",
  "npc.tony_fridge.name": "Tony the Fridge",
  "npc.mehana_waiter.name": "Waiter Kiro",

  "look.apartment.wallpaper": "The wallpaper is peeling with the quiet dignity of a retired minister.",
  "look.apartment.window": "A window to fresh air, as far as the district allows.",
  "look.apartment.accordion": "My accordion. The only thing I ever played honestly.",
  "look.apartment.mirror": "The mirror shows him in three pieces. Coalition energy.",
  "look.apartment.tv": "The TV is explaining that the situation is stable, but in an emergency way.",
  "look.apartment.wardrobe": "The wardrobe guards clothes from a time when Bai Mitko still had a plan B.",
  "look.apartment.table": "A table for bills, promises, and other paper tragedies.",
  "look.apartment.rakia_bottle": "Homemade rakia. No label, because truth needs no paperwork.",
  "look.apartment.bed": "A sofa-bed. Coalition by day, governing majority by night.",
  "msg.apartment.nap": "Bai Mitko took an official nap. The world has one horizon again.",
  "msg.apartment.window_opened": [
    "Mmmm. Smells like elections.",
    "Someone must have aired out the coalition again."
  ],
  "look.apartment.poster": "VOTE MITKO: AT LEAST YOU KNOW HIM. A strong platform when the village has run out of options.",
  "look.square.poster_board": "Poster over poster over promise. Archaeology of hope.",
  "look.square.fountain": "The fountain does not work, but at least it is not stealing electricity.",
  "look.square.kiosk": "The kiosk knows more news than it sells.",
  "look.square.statue": "A monument to a local hero from the bust upward. Below that, the budget ran out.",
  "look.square.old_men_bench": "The bench is the only polling institute with a permanent sample.",
  "look.square.election_notice": "It says the election is transparent. The paper looks slightly cloudy.",
  "look.mehana.oil": "Sunflower oil. In this country, both salad and careers slide on it.",
  "look.mehana.water_jug": "Water. The most dangerous liquid in the tavern because it raises suspicion.",
  "look.mehana.table": "Bai Mitko has taken a seat with the confidence of a man whose bill belongs to the next administration.",
  "look.npc.mehana_waiter": "Kiro remembers every order and forgets every request for a receipt.",
  "look.npc.baba_stoyanka": "Baba Stoyanka looks like she survived three regimes and four renovations of the square.",
  "look.npc.tony_fridge": "Tony the Fridge. A man with the back of a wardrobe and the liver of a municipal budget.",

  "msg.walk": "Bai Mitko walks like a man who owes money in three directions.",
  "msg.no_use": "Morally questionable, administratively impossible.",
  "msg.taken": "Taken. This looks useful, or at least deniable.",
  "msg.already_taken": "Already pocketed. Bai Mitko does not repeat theft without a reason.",
  "msg.need_talk": "That is not a conversation. That is infrastructure.",
  "msg.scene_saved": "Saved.",
  "msg.mehana.rakia_ordered": "A rakia arrives. The glass is small, but its mandate is strong.",
  "msg.rakia.level.daisy": "To your health. And to quorum.",
  "msg.rakia.level.merry": "Now my platform has finally grown broader.",
  "msg.rakia.level.tipsy": "I am not swaying. The coalition keeps moving the floor.",
  "msg.rakia.level.plastered": "Quiet! I am negotiating with the wardrobe.",
  "msg.water_recovery": "Water performs no miracles, but Bai Mitko at least remembers which floor is his.",
  "msg.mehana.tripe_soup": "The tripe soup arrives like a warm parliamentary committee. Bai Mitko regains a few percentage points.",
  "msg.mehana.shopska_ordered": "The Shopska arrives under a landslide of cheese. The tomatoes request observer status.",
  "msg.oil_used": "Bai Mitko drank the oil with the expression of a man investing in the future.",
  "msg.accordion_tony": "The accordion tore through the silence. Tony remembered youth and a waitress from 1998.",
  "msg.water_swap_success": "Tony respected a man who could drink like a refrigerator. Bai Mitko respected plumbing.",
  "msg.water_swap_missing": "Without a distraction, this looks like crime instead of politics.",
  "msg.scene_not_ready": "This part of the municipality is still under repair of the repair.",

  "quest.chapter1.main.title": "Win the village election before your creditors find you.",
  "quest.chapter1.fake_diploma.title": "Create a diploma impressive enough for voters who never read diplomas.",
  "quest.chapter1.baba_vote.title": "Convince Baba Stoyanka that your corruption is at least traditional.",
  "quest.chapter1.tony_vote.title": "Win Tony the Fridge's support without losing consciousness.",
  "quest.chapter1.journalist.title": "Survive the journalist's questions without accidentally telling the truth.",
  "quest.chapter1.ballot_box.title": "Find the missing ballot box before someone ferments democracy.",

  "dialogue.common.back": "Back.",
  "dialogue.waiter.start": "Kiro: The menu is advisory. The bill is final.",
  "dialogue.waiter.choice.rakia": "One rakia.",
  "dialogue.waiter.choice.shopska": "One Shopska salad.",
  "dialogue.waiter.choice.tripe_soup": "Tripe soup for stabilization.",
  "dialogue.waiter.choice.people": "Who else is drinking here?",
  "dialogue.waiter.choice.leave": "I am only inspecting the prices.",
  "dialogue.waiter.people": "Kiro: Tony drinks at the large table. The others form a temporary coalition around whoever is paying.",
  "dialogue.tony.start": "Tony: If you came for support, show capacity first. Around here capacity is measured in glasses.",
  "dialogue.tony.choice.challenge": "Let's discuss the glasses.",
  "dialogue.tony.choice.politics": "Tony, the village needs stability.",
  "dialogue.tony.choice.leave": "I'll stabilize from outside.",
  "dialogue.tony.politics": "Tony: Stability is in the fridge. You open it, it is still cold.",
  "dialogue.tony.challenge": "Tony: We drink. Whoever blinks votes for the old mayor.",
  "dialogue.tony.choice.accept": "I accept. My liver is coalition-ready.",
  "dialogue.tony.choice.refuse": "Not yet. I need campaign preparation.",
  "dialogue.baba.start": "Baba Stoyanka: You are all crooks, but some of you at least say hello.",
  "dialogue.baba.choice.tradition": "My corruption is traditional.",
  "dialogue.baba.choice.promise": "I will renovate the renovation.",
  "dialogue.baba.choice.leave": "I'll come back, unless they find me first.",
  "dialogue.baba.tradition": "Baba Stoyanka: Traditional, you say? Then at least leave something for the children.",
  "dialogue.baba.promise": "Baba Stoyanka: They have been renovating that renovation since my goat was young."
};
